# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turbolift < Formula
  desc "A simple tool to help apply changes across many GitHub repositories simultaneously"
  homepage "https://github.com/Skyscanner/turbolift"
  version "2.1.1"
  license "Apache 2.0"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Skyscanner/turbolift/releases/download/2.1.1/turbolift_2.1.1_Darwin_x86_64.tar.gz"
      sha256 "dd3b841a48bcf321190b3936c891fd64d7b801224dee7ffce876d15c2246c3d9"

      def install
        bin.install "turbolift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Skyscanner/turbolift/releases/download/2.1.1/turbolift_2.1.1_Darwin_arm64.tar.gz"
      sha256 "c2c20a0c3cf6d3b4935d73c83437c2d88c583275787e69d894e342daa143dcc3"

      def install
        bin.install "turbolift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Skyscanner/turbolift/releases/download/2.1.1/turbolift_2.1.1_Linux_x86_64.tar.gz"
      sha256 "eb213df4c3700b0e329ba50a4ad8fe4400d020dab6cdb31cc2f05afa3f739689"

      def install
        bin.install "turbolift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Skyscanner/turbolift/releases/download/2.1.1/turbolift_2.1.1_Linux_arm64.tar.gz"
      sha256 "6a2fce135e8e08cf85fabc325fb9ee9f819ba04338516a0a6886fed443506062"

      def install
        bin.install "turbolift"
      end
    end
  end
end
